/* --------------------------------- Cities --------------------------------- */
export const citiesInKSA = [
  "Riyadh",
  "Jeddah",
  "Mecca",
  "Medina",
  "Dammam",
  "Khobar",
  "Buraidah",
  "Khafji",
  "Tabuk",
  "Ha'il",
  "Al-Kharj",
  "Yanbu",
  "Jubail",
  "Al-Khobar",
  "Ta'if",
  "Najran",
  "Al Qatif",
  "Al Mubarraz",
  "Khamis Mushait",
  "Al-Ahsa",
  "Abha",
  "Arar",
  "Jizan",
  "Sakakah",
  "Al Bahah",
  "Dhahran",
  "Al Jubail",
  "Hofuf",
  "Al Qunfudhah",
  "Al Badayea",
  "Unaizah",
  "Ras Tanura",
  "Qatif",
  "Tarut",
  "Al Namas",
  "Al Majma'ah",
  "Al Qunfudhah",
  "Rabigh",
  "Dhurma",
  "Layla",
  "Al Wajh",
  "Al Bukayriyah",
  "Anak",
  "Al-Ula",
  "Turaif",
  "Al Khafji",
  "Ad Dilam",
  "Umm Lajj",
  "Al-Quwayiyah",
  "Dumat Al-Jandal",
  "Afif",
  "Al Jumum",
  "Al Khobar",
  "Sabya",
  "Az Zulfi",
  "Ar Rass",
  "Al Mindak",
  "Al Artaweeiyah",
  "Bishah",
  "Ar Rass",
  "Al Mithnab",
  "As Sulayyil",
  "Al Qaysumah",
  "Tayma",
  "Al Hawiyah",
  "Al Bahah",
  "As Sulayyil",
  "Sayhat",
  "Al Mawain",
  "Al Kharj",
  "Al Majaridah",
  "Tanomah",
  "Qaisumah",
  "Al Lith",
  "Zulfi",
  "Al Hada",
  "Al Jafr",
  "Al Battaliyah",
  "Shaqraa",
  "Mahd Al Dhahab",
  "Al Aflaj",
  "Abu Arish",
  "Al Qarah",
  "Badr Hunayn",
  "Baljurashi",
  "Al Muzaylif",
  "Sajir",
  "Ranyah",
  "Ras Al Khair",
  "Rahimah",
  "Al Duwadimi",
  // ... other smaller towns and villages
];
